##[
  This module provides a `Module` base class, with it's associated subclasses
  that represent compile-time or runtime loaded modules. This classes have
  a `dispatch` interface that gets invoked by a `shell` procedure, which
  receive a sequence of strings as input and returns a sequence of strings
  as output.

  The supported types/subclasses of `Module` are:

  - Static (`StaticModule`): provided at compile-time either by the main binary or a shared
    library.
  - Dynamic (`DynamicModule`): provided at runtime by dynamic/shared libraries. These don't
    require to be linked at compile-time, as they share the same interface
    and so they can be safely searched and loaded on-demand.
  - WASM (`WasmModule` WIP): it will be released on V2.0.0.

  Example of use:

  ```nim
  # Declare a `UserSuppliedDispatch` called `someProc`
  proc someProc(args: seq[string]): seq[string] =
    # Returns the inputs for illustrative purposes
    result = args

  
  var x: Module = StaticModule(
    identity: "someModule",
    version: Version(major: 1, minor: 0, patch: 0),
    importedDispatch: someProc
  )
  echo x.shell("Some", "strings")
  ```
]##
import unishell/buffer
import std/[
  paths,
  files,
  strutils,
  dynlib
]

type
  WrongParameters* = object of ValueError
  CommandFailed* = object of CatchableError

const
  INITCOMMAND*: string = "INIT"
    ## Called on module loading
  SHUTDOWNCOMMAND*: string = "SHUTDOWN"
    ## Called on module unloading
  DYNAMICMODULEEXTENSIONS = [
    "dll",
    "so",
    "dylib"
  ]

type
  UserSuppliedDispatch* = proc (parameters: seq[string]): seq[string] {.raises: [WrongParameters, CommandFailed].}
  ##[
    This is the signature of the procedure that the user should provide to
    Unishell when creating a module with either `StaticModule` or
    `dispatchBoilerplate`.
  ]##
  ImportedDispatch* = proc(input: ptr Buffer, output: ptr Buffer, hostAllocator: HostAllocator) {.cdecl, raises: [WrongParameters, CommandFailed].}
  ##[
    Signature of the dispatch procedure of an external module. It is the one that
    gets imported by the Unishell, and should be generated by the
    `dispatchBoilerplate` template.
  ]##

type
  ModuleType* = enum
    STATIC,
    DYNAMIC
  StaticModulePayloadObj* = object
    dispatch*: UserSuppliedDispatch
  StaticModulePayload* = ref StaticModulePayloadObj
  DynamicModulePayloadObj* = object
    ##[
      Holds the actual pointers to the external module and it's procedure. It is
      declared as it's own object to facilitate the implementation of a custom
      destructor
    ]##
    lib*: LibHandle
      ##[
        Handle for the dynamic library.
      ]##
    dispatch*: ImportedDispatch
  DynamicModulePayload* = ref DynamicModulePayloadObj

proc moduleShutdown(dispatch: UserSuppliedDispatch) {.raises: [].} =
  var input: seq[string] = @[SHUTDOWNCOMMAND]
  try:
    discard dispatch(input)
  except Exception:
    discard
  finally:
    discard

proc moduleShutdown(dispatch: ImportedDispatch) {.raises: [].} =
  var
    input: Buffer = createBuffer(@[SHUTDOWNCOMMAND])
    output: Buffer
  try:
    dispatch(
      addr input,
      addr output,
      hostAllocator
    )
  except Exception:
    discard
  finally:
    discard

proc `=destroy`*(payload: var StaticModulePayloadObj) =
  if payload.dispatch != nil:
    payload.dispatch.moduleShutdown()
    payload.dispatch = nil

proc `=wasMoved`(payload: var StaticModulePayloadObj) =
  payload.dispatch = nil

proc `=destroy`*(payload: var DynamicModulePayloadObj) =
  if payload.dispatch != nil:
    payload.dispatch.moduleShutdown()
    payload.dispatch = nil
  if payload.lib != nil:
    unloadLib(payload.lib)

proc `=wasMoved`(payload: var DynamicModulePayloadObj) =
  payload.dispatch = nil
  payload.lib = nil

type
  Version* = object
    ## Represents a Semantic Version
    major*: int
    minor*: int
    patch*: int
  Module* = ref object
    ##[
    Represents a module, holding its identity and version.
    ]##
    identity*: string
    ##[
      Holds the identity (string that will be used as key in the RCU Table)
      of the module.
    ]##
    version*: Version
    ## The SemVer of the module.
    case kind: ModuleType
    of STATIC:
      staticPayload: StaticModulePayload
    of DYNAMIC:
      path: Path
      dynamicPayload: DynamicModulePayload

type
  ModuleDescription* = ref object
    identity*: string
    version*: Version
    case kind: ModuleType
    of STATIC:
      dispatch: UserSuppliedDispatch
    of DYNAMIC:
      path: Path

proc newModuleDescription*(
  identity: string,
  version: Version,
  dispatch: UserSuppliedDispatch
): ModuleDescription =
  result = ModuleDescription(
    identity: identity,
    version: version,
    kind: STATIC,
    dispatch: dispatch
  )

proc newModuleDescription*(
  identity: string,
  version: Version,
  path: Path
): ModuleDescription {.raises: [ValueError].} =
  var
    splittedFile = splitFile(path)
  if not fileExists(path):
    raise newException(ValueError, "The provided path doesn't exists or it isn't a file")
  if splittedFile.ext in DYNAMICMODULEEXTENSIONS:
    result = ModuleDescription(
      identity: identity,
      version: version,
      kind: DYNAMIC,
      path: path
    )
  else:
    raise newException(ValueError, "The provided file is not supported")

proc loadModule*(description: ModuleDescription): Module =
  var
    lib: LibHandle
    dispatch: ImportedDispatch
  case description.kind
  of STATIC:
    result = Module(
      identity: description.identity,
      version: description.version,
      kind: STATIC,
      staticPayload: StaticModulePayload(
        dispatch: description.dispatch
      )
    )
  of DYNAMIC:
    lib = loadLib($description.path)
    dispatch = cast[ImportedDispatch](
      lib.symAddr("dispatch")
    )
    result = Module(
      identity: description.identity,
      version: description.version,
      kind: DYNAMIC,
      dynamicPayload: DynamicModulePayload(
        lib: lib,
        dispatch: dispatch
      )
    )

proc shell*(module: Module, input: Buffer): Buffer {.raises: [WrongParameters, CommandFailed].} =
  var output: Buffer
  case module.kind
  of STATIC:
    result = createBuffer(
      module.staticPayload.dispatch(input.toSeq())
    )
  of DYNAMIC:
    module.dynamicPayload.dispatch(
      addr input,
      addr output,
      hostAllocator
    )
    result = output

proc shell*(module: Module, parameters: varargs[string, `$`]): seq[string] {.raises: [WrongParameters, CommandFailed].} =
  ##[
    Procedure used to interact with the modules. Example:

    ```nim
    echo someModule.shell("Some", "strings")
    ```
  ]##
  result = toSeq(module.shell(createBuffer(@parameters)))

proc moduleInit*(module: Module, unishellPtr: string) =
  try:
    discard module.shell(INITCOMMAND, unishellPtr)
  finally:
    discard

# =============================================================================
# COMMON TYPES AND PROCEDURES FOR ALL MODULE TYPES
# =============================================================================

proc newVersion*(major: int, minor: int, patch: int): Version =
  result = Version(major: major, minor: minor, patch: patch)

proc `>`*(a, b: Version): bool =
  ## Compares two semantic versions. Returns true if `a` is a newer version than `b`.
  if a.major != b.major:
    return a.major > b.major
  if a.minor != b.minor:
    return a.minor > b.minor
  return a.patch > b.patch

proc `>`*(a, b: Module): bool =
  ## Compares two modules based on their semantic version. Returns true if `a` is a newer version than `b`.
  if a.version > b.version:
    return true
  else:
    return false
  
proc `<`*(a, b: Version): bool =
  ## Compares two semantic versions. Returns true if `a` is an older version than `b`.
  if a.major != b.major:
    return a.major < b.major
  if a.minor != b.minor:
    return a.minor < b.minor
  return a.patch < b.patch
  
proc `<`*(a, b: Module): bool =
  ## Compares two modules based on their semantic version. Returns true if `a` is an older version than `b`.
  if a.version < b.version:
    return true
  else:
    return false
  
proc `==`*(a, b: Version): bool =
  ## Compares two semantic versions. Returns true if `a` and `b` versions are equal.
  if a.major != b.major:
    return false
  if a.minor != b.minor:
    return false
  if a.patch != b.patch:
    return false
  return true
  
proc `==`*(a, b: Module): bool =
  ## Compares two modules based on their semantic version. Returns true if `a` and `b` versions are equal.
  if a.version == b.version:
    return true
  else:
    return false

proc `!=`*(a, b: Version): bool =
  ## Compares two semantic versions. Returns true if `a` and `b` have different versions.
  if a.major != b.major:
    return true
  if a.minor != b.minor:
    return true
  if a.patch != b.patch:
    return true
  return false

proc `!=`*(a, b: Module): bool =
  ## Compares two modules based on their semantic version. Returns true if `a` and `b` have different versions.
  if a.version != b.version:
    return true
  else:
    return false

proc `>=`*(a, b: Version): bool =
  ## Compares two semantic versions. Returns true if `a` is an equal or newer version than `b`.
  if (a > b) or (a == b):
    return true
  else:
    return false

proc `>=`*(a, b: Module): bool =
  ## Compares two modules based on their semantic version. Returns true if `a` is an equal or newer version than `b`.
  if a.version >= b.version:
    return true
  else:
    return false

proc `<=`*(a, b: Version): bool =
  ## Compares two semantic versions. Returns true if `a` is an equal or older version than `b`.
  if (a < b) or (a == b):
    return true
  else:
    return false

proc `<=`*(a, b: Module): bool =
  ## Compares two modules based on their semantic version. Returns true if `a` is an equal or older version than `b`.
  if a.version <= b.version:
    return true
  else:
    return false

proc castPointerToString*(p: pointer): string =
  ##[
    Used to send through the `shell` procedure a pointer to some data structure.
    Example:

    ```nim
    var someString: string = "some text"
    
    echo someModule.shell(castPointerToString(addr someString))
    ```
  ]##
  return $(cast[int](p))

proc castStringToPointer*(p: string): pointer =
  ##[
    Used to receive through the `dispatch` procedure a pointer to some data structure.
    Example:

    ```nim
    var someStringPtr: ptr string = castStringToPointer(arg)
    ```
  ]##
  return cast[pointer](p.parseUInt)

template unishellQuit*() =
  ##[
    A template for freeing all global memory from external modules, based on
    [this issue](https://github.com/nim-lang/Nim/issues/21403#issuecomment-3738505350).
    Use it inside the shutdown logic of your external module.
  ]##
  NimDestroyGlobals()
  GC_FullCollect()
  deallocOsPages()

template dispatchBoilerplate*(userSuppliedProc: UserSuppliedDispatch) =
  ##[
    This template is meant to be used by the modules (`.DLL`, `.SO`, `.WASM`) in
    order to abstract the manual serialization of data, memory management and
    FFI signature.

    The passed procedure must match the `UserSuppliedDispatch` signature.

    Example:

    ```nim
    proc yourLogic(args: seq[string]): seq[string] =
      # Here you write your custom logic
      return args

    # We then call the template. It will handle everything necessary for the FFI
    dispatchBoilerplate(yourLogic)
  ]##
  proc dispatch*(inputBuffer: ptr Buffer, outputBuffer: ptr Buffer, allocator: HostAllocator) {.exportc, dynlib, cdecl, raises: [WrongParameters, CommandFailed].} =
    let
      input: seq[string] = inputBuffer[].toSeq()
      output: seq[string] = userSuppliedProc(input)
    createBufferInPlace(outputBuffer, allocator, output)
