##[
  This module provides a `Module` base class, with it's associated subclasses
  that represent compile-time or runtime loaded modules. This classes have
  a `dispatch` interface that gets invoked by a `shell` procedure, which
  receive a sequence of strings as input and returns a sequence of strings
  as output.

  The supported types/subclasses of `Module` are:

  - Static (`StaticModule`): provided at compile-time either by the main binary or a shared
    library.
  - Dynamic (`DynamicModule`): provided at runtime by dynamic/shared libraries. These don't
    require to be linked at compile-time, as they share the same interface
    and so they can be safely searched and loaded on-demand.
  - WASM (`WasmModule` WIP): it will be released on V2.0.0.

  Example of use:

  ```nim
  # Declare a `UserSuppliedDispatch` called `someProc`
  proc someProc(args: seq[string]): seq[string] =
    # Returns the inputs for illustrative purposes
    result = args

  
  var x: Module = StaticModule(
    identity: "someModule",
    version: Version(major: 1, minor: 0, patch: 0),
    importedDispatch: someProc
  )
  echo x.shell("Some", "strings")
  ```
]##
import unishell/buffer
import std/[
  paths,
  files,
  strutils
]

const
  INITCOMMAND*: string = "INIT"
    ## Called on module loading
  SHUTDOWNCOMMAND*: string = "SHUTDOWN"
    ## Called on module unloading

type
  UserSuppliedDispatch* = proc (parameters: seq[string]): seq[string]
  ##[
    This is the signature of the procedure that the user should provide to
    Unishell when creating a module with either `StaticModule` or
    `dispatchBoilerplate`.
  ]##
  Version* = object
    ## Represents a Semantic Version
    major*: int
    minor*: int
    patch*: int
  Module* = ref object of RootObj
    ##[
    Represents a module, holding its identity and version.
    ]##
    identity*: string
    ##[
      Holds the identity (string that will be used as key in the RCU Table)
      of the module.
    ]##
    version*: Version
    ## The SemVer of the module.

method dispatch*(module: Module, input: Buffer): Buffer {.base.} =
  ## Base dispatch method to be overridden by subclasses
  quit "Dispatch called on base Module!"

# Forward declaration to use it within destructors later
proc moduleShutdown(module: UserSuppliedDispatch) {.raises: [].}

# =============================================================================
# COMMON TYPES, PROCEDURES AND TEMPLATES FOR COMPILED MODULES
# =============================================================================

#[
  This section defines the cross-boundary data gateway for `dispatch`
  operations. It provides the host-side allocation hooks and a module-side
  template to  handle the serialization, memory allocation requests, and
  raw byte-copying  required to pass data safely between the main binary and
  external modules.
]#

type
  HostsAllocator* = proc(buffer: ptr Buffer, len: int, cap: int) {.cdecl.}
  ##[
    Signature of the procedure used to allocate the necessary memory on the host
    for the output of a dispatch operation from the external module. Internally,
    it just calls `preAllocateBuffer` from the `buffers.nim` module in the host.
  ]##
  ImportedDispatch* = proc(input: ptr Buffer, output: ptr Buffer, hostAllocator: HostsAllocator) {.cdecl.}
  ##[
    Signature of the dispatch procedure of a external module. It is the one that
    gets imported by the Unishell, and should be generated by the
    `dispatchBoilerplate` template.
  ]##
proc hostsAllocator*(output: ptr Buffer, len: int, cap: int) {.cdecl.} =
  ##[
    Wraps the library-provided pre-allocation logic on the host to pass it to
    the external module's dispatch method.
  ]##
  preAllocateBuffer(output, len, cap)

# Forward declaration to use it within destructors later
proc moduleShutdown(module: ImportedDispatch) {.raises: [].}

template unishellQuit*() =
  ##[
    A template for freeing all global memory from external modules, based on
    [this issue](https://github.com/nim-lang/Nim/issues/21403#issuecomment-3738505350).
    Use it inside the shutdown logic of your external module.
  ]##
  NimDestroyGlobals()
  GC_FullCollect()
  deallocOsPages()

template dispatchBoilerplate*(userSuppliedProc: UserSuppliedDispatch) =
  ##[
    This template is meant to be used by the modules (`.DLL`, `.SO`, `.WASM`) in
    order to abstract the manual serialization of data, memory management and
    FFI signature.

    The passed procedure must match the `UserSuppliedDispatch` signature.

    Example:

    ```nim
    proc yourLogic(args: seq[string]): seq[string] =
      # Here you write your custom logic
      return args

    # We then call the template. It will handle everything necessary for the FFI
    dispatchBoilerplate(yourLogic)
  ]##
  proc dispatch*(inputBuffer: ptr Buffer, outputBuffer: ptr Buffer, allocator: HostsAllocator) {.exportc, dynlib, cdecl.} =
    let
      input: seq[string] = inputBuffer[].toSeq()
      output: seq[string] = userSuppliedProc(input)
      outputLen: int = output.len()
    var outputCap: int = 0
    for element in output:
      outputCap += element.len()
    allocator(outputBuffer, outputLen, outputCap)
    # Auxiliary variables for the copy of data
    var
      dataAddress: uint = 0
      elementOffset: uint = 0
    if outputLen > 0:
      dataAddress = cast[uint](outputBuffer[].data)
      for index, element in pairs(output):
        outputBuffer.sizes[index] = element.len
        if element.len > 0:
          outputBuffer.offsets[index] = elementOffset
          copyMem(cast[pointer](dataAddress + elementOffset), addr element[0], element.len)
        elementOffset += (element.len).uint

# =============================================================================
# STATIC MODULES
# =============================================================================

type
  StaticModulePayloadObj* = object
    importedDispatch*: UserSuppliedDispatch
  StaticModulePayload* = ref StaticModulePayloadObj
  StaticModule* = ref object of Module
    ##[
      Object that represents a module from the main binary. This is used to
      provide access to certain procedures to external modules, and also to
      create default modules that could be updated later with external modules.
      Example:

      ```nim
      # Declare a `UserSuppliedDispatch` called `someProc`
      proc someProc(args: seq[string]): seq[string] =
        # Returns the inputs for illustrative purposes
        result = args

  
      var x: Module = StaticModule(
        identity: "someModule",
        version: Version(major: 1, minor: 0, patch: 0),
        importedDispatch: someProc
      )
      ```
    ]##
    payload: StaticModulePayload

proc `=destroy`*(payload: var StaticModulePayloadObj) =
  if payload.importedDispatch != nil:
    payload.importedDispatch.moduleShutdown()
    payload.importedDispatch = nil

proc loadStaticModule(identity: string, version: Version, importedDispatch: UserSuppliedDispatch): StaticModule =
  new(result)
  result.identity = identity
  result.version = version
  result.payload = new(StaticModulePayload)
  result.payload.importedDispatch = importedDispatch

method dispatch*(
  module: StaticModule,
  input: Buffer
): Buffer =
  result = createBuffer(
    module.payload.importedDispatch(input.toSeq())
  )

# =============================================================================
# DYNAMIC/SHARED LIBRARY BASED MODULES
# =============================================================================

const dynamicModuleExtensions = [
  "dll",
  "so",
  "dylib"
]

# When this option is enabled, the DynamicModule type doesn't exists, and therefore the loadDynamicModule should return a Module, which is a type that exists
when defined(unishellDisableDynamicModules):
  proc loadDynamicModule(path: Path, identity: string, version: Version): Module =
    result = nil
else:
  import std/dynlib

  type
    DynamicModulePayloadObj* = object
      ##[
        Holds the actual pointers to the external module and it's procedure. It is
        declared as it's own object to facilitate the implementation of a custom
        destructor
      ]##
      lib*: LibHandle
        ##[
          Handle for the dynamic library.
        ]##
      importedDispatch*: ImportedDispatch
    DynamicModulePayload* = ref DynamicModulePayloadObj
    DynamicModule* = ref object of Module
      ##[
        Object that represents an external module in the form of a
        dynamic/shared library. It is not meant to be created manually by the
        user.
      ]##
      path*: Path
      ##[
        Absolute path to the dynamic library. It is used to identify the file
        that corresponds to the currently loaded module.
      ]##
      payload*: DynamicModulePayload 

  proc `=destroy`*(payload: var DynamicModulePayloadObj) =
    if payload.importedDispatch != nil:
      payload.importedDispatch.moduleShutdown()
      payload.importedDispatch = nil
    if payload.lib != nil:
      unloadLib(payload.lib)

  method dispatch*(
    module: DynamicModule,
    input: Buffer
  ): Buffer =
    var output: Buffer
    if module.payload.importedDispatch != nil:
      module.payload.importedDispatch(
        addr input,
        addr output,
        hostsAllocator
      )
      result = output
    else:
      result = createBuffer(@[])

  proc loadDynamicModule(path: Path, identity: string, version: Version): DynamicModule =
    var splittedFile = splitFile(path)
    if fileExists(path) and (splittedFile.ext in dynamicModuleExtensions):
      new(result)
      result.identity = identity
      result.version = version
      result.payload = new(DynamicModulePayload)
      result.payload.lib = loadLib($path)
      result.payload.importedDispatch = cast[ImportedDispatch](
        result.payload.lib.symAddr("dispatch")
      )
    else:
      result = nil

# =============================================================================
# WASM BASED MODULES (WIP)
# =============================================================================

const wasmModuleExtensions = [
  "wasm"
]

# When this option is enabled, the WasmModule type doesn't exists, and therefore the loadWasmModule should return a Module, which is a type that exists
when defined(unishellDisableWasmModules):
  proc loadWasmModule(path: Path, identity: string, version: Version): Module =
    result = nil
else:
  proc loadWasmModule(path: Path, identity: string, version: Version): Module =
    var splittedFile = splitFile(path)
    if fileExists(path) and (splittedFile.ext in wasmModuleExtensions):
      result = nil
    else:
      result = nil

# =============================================================================
# COMMON TYPES AND PROCEDURES FOR ALL MODULE TYPES
# =============================================================================

proc shell*(module: Module, parameters: varargs[string, `$`]): seq[string] {.cdecl.} =
  ##[
    Procedure used to interact with the modules. Example:

    ```nim
    echo someModule.shell("Some", "strings")
    ```
  ]##
  result = toSeq(module.dispatch(createBuffer(@parameters)))

proc moduleInit(module: Module) =
  try:
    discard module.shell(INITCOMMAND)
  finally:
    discard

proc moduleShutdown(module: UserSuppliedDispatch) {.raises: [].} =
  var input: seq[string] = @[SHUTDOWNCOMMAND]
  try:
    discard module(input)
  except Exception:
    discard
  finally:
    discard

proc moduleShutdown(module: ImportedDispatch) {.raises: [].} =
  var
    input: Buffer = createBuffer(@[SHUTDOWNCOMMAND])
    output: Buffer
  try:
    module(
      addr input,
      addr output,
      hostsAllocator
    )
  except Exception:
    discard
  finally:
    discard

type
  ModuleDescription* = ref object of RootObj
    identity*: string
    version*: Version
  StaticModuleDescription* = ref object of ModuleDescription
    dispatch*: UserSuppliedDispatch
  ExternalModuleDescription* = ref object of ModuleDescription
    path*: Path

proc newModuleDescription*(
  identity: string,
  version: Version,
  dispatch: UserSuppliedDispatch
): StaticModuleDescription =
  new(result)
  result.identity = identity
  result.version = version
  result.dispatch = dispatch

proc newModuleDescription*(
  identity: string,
  version: Version,
  path: Path
): ExternalModuleDescription =
  new(result)
  result.identity = identity
  result.version = version
  result.path = path
  
method loadModule*(description: ModuleDescription): Module {.base.} =
  ## Base loadModule method to be overridden by subclasses
  quit "LoadModule called on base ModuleDescription!"

method loadModule*(description: StaticModuleDescription): Module =
  result = loadStaticModule(
    description.identity,
    description.version,
    description.dispatch
  )
  result.moduleInit()

method loadModule*(description: ExternalModuleDescription): Module =
  result = nil
  result = loadDynamicModule(
    description.path,
    description.identity,
    description.version
  )
  if result == nil:
    result = loadWasmModule(
      description.path,
      description.identity,
      description.version
    )
  if result == nil:
    raise newException(ValueError, "Error: createModule: couldn\'t load module")
  else:
    result.moduleInit()
  
  
proc `>`*(a, b: Version): bool =
  ## Compares two semantic versions. Returns true if `a` is a newer version than `b`.
  if a.major != b.major:
    return a.major > b.major
  if a.minor != b.minor:
    return a.minor > b.minor
  return a.patch > b.patch

proc `>`*(a, b: Module): bool =
  ## Compares two modules based on their semantic version. Returns true if `a` is a newer version than `b`.
  if a.version > b.version:
    return true
  else:
    return false
  
proc `<`*(a, b: Version): bool =
  ## Compares two semantic versions. Returns true if `a` is an older version than `b`.
  if a.major != b.major:
    return a.major < b.major
  if a.minor != b.minor:
    return a.minor < b.minor
  return a.patch < b.patch
  
proc `<`*(a, b: Module): bool =
  ## Compares two modules based on their semantic version. Returns true if `a` is an older version than `b`.
  if a.version < b.version:
    return true
  else:
    return false
  
proc `==`*(a, b: Version): bool =
  ## Compares two semantic versions. Returns true if `a` and `b` versions are equal.
  if a.major != b.major:
    return false
  if a.minor != b.minor:
    return false
  if a.patch != b.patch:
    return false
  return true
  
proc `==`*(a, b: Module): bool =
  ## Compares two modules based on their semantic version. Returns true if `a` and `b` versions are equal.
  if a.version == b.version:
    return true
  else:
    return false

proc `!=`*(a, b: Version): bool =
  ## Compares two semantic versions. Returns true if `a` and `b` have different versions.
  if a.major != b.major:
    return true
  if a.minor != b.minor:
    return true
  if a.patch != b.patch:
    return true
  return false

proc `!=`*(a, b: Module): bool =
  ## Compares two modules based on their semantic version. Returns true if `a` and `b` have different versions.
  if a.version != b.version:
    return true
  else:
    return false

proc `>=`*(a, b: Version): bool =
  ## Compares two semantic versions. Returns true if `a` is an equal or newer version than `b`.
  if (a > b) or (a == b):
    return true
  else:
    return false

proc `>=`*(a, b: Module): bool =
  ## Compares two modules based on their semantic version. Returns true if `a` is an equal or newer version than `b`.
  if (a > b) or (a == b):
    return true
  else:
    return false

proc `<=`*(a, b: Version): bool =
  ## Compares two semantic versions. Returns true if `a` is an equal or older version than `b`.
  if (a < b) or (a == b):
    return true
  else:
    return false

proc `<=`*(a, b: Module): bool =
  ## Compares two modules based on their semantic version. Returns true if `a` is an equal or older version than `b`.
  if (a < b) or (a == b):
    return true
  else:
    return false

proc castPointerToString*(p: pointer): string =
  ##[
    Used to send through the `shell` procedure a pointer to some data structure.
    Example:

    ```nim
    var someString: string = "some text"
    
    echo someModule.shell(castPointerToString(addr someString))
    ```
  ]##
  return $(cast[int](p))

proc castStringToPointer*(p: string): pointer =
  ##[
    Used to receive through the `dispatch` procedure a pointer to some data structure.
    Example:

    ```nim
    var someStringPtr: ptr string = castStringToPointer(arg)
    ```
  ]##
  return cast[pointer](p.parseUInt)
