##[
  This module provides a `Module` base class, with it's associated subclasses
  that represent compile-time or runtime loaded modules. This classes have
  a `dispatch` interface that gets invoked by a `shell` procedure, which
  receive a sequence of strings as input and returns a sequence of strings
  as output.

  The supported types/subclasses of `Module` are:

  - Static (`StaticModule`): provided at compile-time either by the main binary or a shared
    library.
  - Dynamic (`DynamicModule`): provided at runtime by dynamic/shared libraries. These don't
    require to be linked at compile-time, as they share the same interface
    and so they can be safely searched and loaded on-demand.
  - WASM (`WasmModule` WIP): it will be released on V2.0.0.

  Example of use:

  ```nim
  # Declare a `UserSuppliedDispatch` called `someProc`
  proc someProc(args: seq[string]): seq[string] =
    # Returns the inputs for illustrative purposes
    result = args

  
  var x: Module = StaticModule(
    identity: "someModule",
    version: Version(major: 1, minor: 0, patch: 0),
    importedDispatch: someProc
  )
  echo x.shell("Some", "strings")
  ```
]##
when not defined(gcArc) and not defined(gcOrc) and not defined(gcAtomicArc):
  {.error: "module.nim requires to be compiled with --mm:arc, --mm:orc or --mm:atomicArc".}
import unishell/buffer
import std/[
  paths,
  files,
  strutils,
  dynlib
]
export buffer

type
  WrongParameters* = object of ValueError
  CommandFailed* = object of CatchableError

const
  INITCOMMAND*: string = "INIT"
    ## Called on module loading
  SHUTDOWNCOMMAND*: string = "SHUTDOWN"
    ## Called on module unloading
  DYNAMICMODULEEXTENSIONS = [
    ".dll",
    ".so",
    ".dylib"
  ]

type
  UserSuppliedDispatch* = proc (parameters: seq[string]): seq[string] {.raises: [WrongParameters, CommandFailed].}
  ##[
    This is the signature of the procedure that the user should provide to
    Unishell when creating a module with the `dispatchBoilerplate` template.
  ]##
  ImportedDispatch* = proc(input: Buffer, output: var Buffer, hostAllocator: HostAllocator = hostAllocator) {.cdecl, raises: [WrongParameters, CommandFailed].}
  ##[
    Signature of the dispatch procedure of an external module. It is the one that
    gets imported by the Unishell, and should be generated by the
    `dispatchBoilerplate` template.
  ]##

type
  Version* = object
    major*: int
    minor*: int
    patch*: int
  ModuleType* = enum
    STATIC,
    DYNAMIC
  Payload* = object
    dispatch*: ImportedDispatch
    case kind: ModuleType
    of STATIC:
      discard
    of DYNAMIC:
      path*: Path
      lib*: LibHandle
  Module* = ref object
    ##[
    Represents a module, holding its identity and version.
    ]##
    identity*: string
    ##[
      Holds the identity (string that will be used as key in the RCU Table)
      of the module.
    ]##
    version*: Version
    ## The SemVer of the module.
    payload*: Payload

proc `=destroy`*(payload: var Payload) =
  var
    input: Buffer
    output: Buffer
  input.newBuffer(@[SHUTDOWNCOMMAND])
  try:
    payload.dispatch(input, output, hostAllocator)
  except Exception:
    discard
  finally:
    input.dallocDarray(0)
    output.dallocDarray(0)
    payload.dispatch = nil
  case payload.kind
  of STATIC:
    discard
  of DYNAMIC:
    payload.path.reset()
    if payload.lib != nil:
      unloadLib(payload.lib)
      payload.lib = nil

proc `=wasMoved`*(payload: var Payload) =
  payload.dispatch = nil
  case payload.kind
  of STATIC:
    discard
  of DYNAMIC:
    payload.path.reset()
    payload.lib = nil

proc `=sink`*(dest: var Payload, src: Payload) =
  `=destroy`(dest)
  wasMoved(dest)
  dest.dispatch = src.dispatch
  case dest.kind
  of STATIC:
    discard
  of DYNAMIC:
    if src.kind == dest.kind:
      dest.path = src.path
      dest.lib = src.lib

proc `=copy`*(dest: var Payload, src: Payload) =
  if dest.dispatch != src.dispatch:
    dest.dispatch = src.dispatch
  case dest.kind
  of STATIC:
    discard
  of DYNAMIC:
    if src.kind == dest.kind:
      dest.path = src.path
      dest.lib = src.lib

proc `=dup`*(dest: Payload): Payload =
  return dest


proc checkLibraryFile(kind: ModuleType, path: Path): bool {.raises: [ValueError].} =
  var aux = splitFile(path)
  case kind
  of STATIC:
    raise newException(ValueError, "STATIC Modules don't have an associated filetype")
  of DYNAMIC:
    if (fileExists(path)) and (aux.ext in DYNAMICMODULEEXTENSIONS):
      return true
    else:
      return false

proc shell*(module: Module, input: Buffer, output: var Buffer, allocator: HostAllocator) {.raises: [WrongParameters, CommandFailed].} =
  module.payload.dispatch(input, output, allocator)

proc shell*(module: Module, parameters: varargs[string, `$`]): seq[string] {.raises: [WrongParameters, CommandFailed].} =
  ##[
    This is a language specific, high level wrapper for the actual shell
    procedure. It is meant to ease the translation of Nim's seq[string] to
    a Buffer object. Example:

    ```nim
    echo someModule.shell("Some", "strings")
    ```
  ]##
  var
    input: Buffer
    output: Buffer
    outputView: BufferView
    outputSeq: seq[string]
    wrongParameterFlag: bool = false
    wrongParameterMsg: string
    commandFailedFlag: bool = false
    commandFailedMsg: string
  try:
    input.newBuffer(@parameters)
    module.shell(input, output, hostAllocator)
  except WrongParameters as e:
    wrongParameterFlag = true
    wrongParameterMsg = e.msg
  except CommandFailed as e:
    commandFailedFlag = true
    commandFailedMsg = e.msg
  finally:
    if (not wrongParameterFlag) and (not commandFailedFlag):
      outputView = output.newBufferView()
      outputSeq = outputView.toSeq()
    else:
      input.dallocDarray(0)
      output.dallocDarray(0)
      if wrongParameterFlag:
        raise newException(WrongParameters, wrongParameterMsg)
      if commandFailedFlag:
        raise newException(CommandFailed, commandFailedMsg)
  return outputSeq

proc loadModule*(identity: string, version: Version, dispatch: ImportedDispatch, extraArg: string = ""): Module {.raises: [].} =
  var aux: Module
  aux = Module(
    identity: identity,
    version: version,
    payload: Payload(dispatch: dispatch, kind: STATIC)
  )
  try:
    discard aux.shell(INITCOMMAND, extraArg)
  except Exception:
    discard
  return aux

proc loadModule*(identity: string, version: Version, kind: ModuleType, path: Path, extraArg: string = ""): Module {.raises: [ValueError].} =
  var aux: Module
  if checkLibraryFile(kind, path):
    case kind
    of STATIC:
      raise newException(ValueError, "Static modules are not defined with paths. Omit the kind and pass the \'ImportedDispatch\'")
    of DYNAMIC:
      aux = Module(
        identity: identity,
        version: version,
        payload: Payload(dispatch: nil, kind: kind, path: path, lib: nil)
      )
      aux.payload.lib = loadLib($path)
      aux.payload.dispatch = cast[ImportedDispatch](
        aux.payload.lib.symAddr("dispatch")
      )
    try:
      discard aux.shell(INITCOMMAND, extraArg)
    except Exception:
      discard
  else:
    raise newException(ValueError, "The provided file either doesn\'t exist or it's extension doesn't match the module\'s type")
  return aux

# =============================================================================
# COMMON TYPES AND PROCEDURES FOR ALL MODULE TYPES
# =============================================================================

proc newVersion*(major: int, minor: int, patch: int): Version =
  result = Version(major: major, minor: minor, patch: patch)

proc `>`*(a, b: Version): bool =
  ## Compares two semantic versions. Returns true if `a` is a newer version than `b`.
  if a.major != b.major:
    return a.major > b.major
  if a.minor != b.minor:
    return a.minor > b.minor
  return a.patch > b.patch

proc `>`*(a, b: Module): bool =
  ## Compares two modules based on their semantic version. Returns true if `a` is a newer version than `b`.
  if a.version > b.version:
    return true
  else:
    return false
  
proc `<`*(a, b: Version): bool =
  ## Compares two semantic versions. Returns true if `a` is an older version than `b`.
  if a.major != b.major:
    return a.major < b.major
  if a.minor != b.minor:
    return a.minor < b.minor
  return a.patch < b.patch
  
proc `<`*(a, b: Module): bool =
  ## Compares two modules based on their semantic version. Returns true if `a` is an older version than `b`.
  if a.version < b.version:
    return true
  else:
    return false
  
proc `==`*(a, b: Version): bool =
  ## Compares two semantic versions. Returns true if `a` and `b` versions are equal.
  if a.major != b.major:
    return false
  if a.minor != b.minor:
    return false
  if a.patch != b.patch:
    return false
  return true
  
proc `==`*(a, b: Module): bool =
  ## Compares two modules based on their semantic version. Returns true if `a` and `b` versions are equal.
  if a.version == b.version:
    return true
  else:
    return false

proc `!=`*(a, b: Version): bool =
  ## Compares two semantic versions. Returns true if `a` and `b` have different versions.
  if a.major != b.major:
    return true
  if a.minor != b.minor:
    return true
  if a.patch != b.patch:
    return true
  return false

proc `!=`*(a, b: Module): bool =
  ## Compares two modules based on their semantic version. Returns true if `a` and `b` have different versions.
  if a.version != b.version:
    return true
  else:
    return false

proc `>=`*(a, b: Version): bool =
  ## Compares two semantic versions. Returns true if `a` is an equal or newer version than `b`.
  if (a > b) or (a == b):
    return true
  else:
    return false

proc `>=`*(a, b: Module): bool =
  ## Compares two modules based on their semantic version. Returns true if `a` is an equal or newer version than `b`.
  if a.version >= b.version:
    return true
  else:
    return false

proc `<=`*(a, b: Version): bool =
  ## Compares two semantic versions. Returns true if `a` is an equal or older version than `b`.
  if (a < b) or (a == b):
    return true
  else:
    return false

proc `<=`*(a, b: Module): bool =
  ## Compares two modules based on their semantic version. Returns true if `a` is an equal or older version than `b`.
  if a.version <= b.version:
    return true
  else:
    return false

# =============================================================================
# HELPER PROCEDURES & TEMPLATES
# =============================================================================

proc castPointerToString*(p: pointer): string =
  ##[
    Used to send through the `shell` procedure a pointer to some data structure.
    Example:

    ```nim
    var someString: string = "some text"
    
    echo someModule.shell(castPointerToString(addr someString))
    ```
  ]##
  return $(cast[int](p))

proc castStringToPointer*(p: string): pointer =
  ##[
    Used to receive through the `dispatch` procedure a pointer to some data structure.
    Example:

    ```nim
    var someObjectPtr: ptr SomeObject = castStringToPointer(arg)
    ```
  ]##
  return cast[pointer](p.parseUInt)

template dispatchBoilerplate*(userSuppliedProc: UserSuppliedDispatch) =
  ##[
    This template is meant to be used by the modules (`.DLL`, `.SO`, `.WASM`) in
    order to abstract the manual serialization of data, memory management and
    FFI signature.

    The passed procedure must match the `UserSuppliedDispatch` signature.

    Example:

    ```nim
    proc yourLogic(args: seq[string]): seq[string] =
      # Here you write your custom logic
      return args

    # We then call the template. It will handle everything necessary for the FFI
    dispatchBoilerplate(yourLogic)
  ]##
  proc dispatch*(inputBuffer: Buffer, outputBuffer: var Buffer, allocator: HostAllocator) {.exportc, dynlib, cdecl, raises: [WrongParameters, CommandFailed].} =
    let
      inputView: BufferView = inputBuffer.newBufferView()
      inputSeq: seq[string] = inputView.toSeq()
      output: seq[string] = userSuppliedProc(inputSeq)
    outputBuffer.newBuffer(output, allocator)
